In [1]:
import pandas as pd
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("nba.csv")

In [3]:
df.head(4)

Name            Team  Number Position  Age  Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25  06-Feb     180   
1    Jae Crowder  Boston Celtics      99       SF   25  06-Jun     235   
2   John Holland  Boston Celtics      30       SG   27  06-May     205   
3    R.J. Hunter  Boston Celtics      28       SG   22  06-May     185   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0

In [5]:
df.isna().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [7]:
df.shape

(457, 9)

In [8]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [11]:
print(df['Position'].value_counts())

SG    102
PF    100
PG     92
SF     85
C      78
Name: Position, dtype: int64


In [13]:
one_hot=pd.get_dummies(df.Position)
one_hot

C  PF  PG  SF  SG
0    0   0   1   0   0
1    0   0   0   1   0
2    0   0   0   0   1
3    0   0   0   0   1
4    0   1   0   0   0
..  ..  ..  ..  ..  ..
452  0   1   0   0   0
453  0   0   1   0   0
454  0   0   1   0   0
455  1   0   0   0   0
456  1   0   0   0   0

[457 rows x 5 columns]

In [14]:
merged=pd.concat([df,one_hot],axis='columns')
merged

Name            Team  Number Position  Age  Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25  06-Feb     180   
1      Jae Crowder  Boston Celtics      99       SF   25  06-Jun     235   
2     John Holland  Boston Celtics      30       SG   27  06-May     205   
3      R.J. Hunter  Boston Celtics      28       SG   22  06-May     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29  06-Oct     231   
..             ...             ...     ...      ...  ...     ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20  06-Oct     234   
453   Shelvin Mack       Utah Jazz       8       PG   26  06-Mar     203   
454      Raul Neto       Utah Jazz      25       PG   24  06-Jan     179   
455   Tibor Pleiss       Utah Jazz      21        C   26  07-Mar     256   
456    Jeff Withey       Utah Jazz      24        C   26     7-0     231   

               College     Salary  C  PF  PG  SF  SG  
0                Texas  7730337.0  0   0   1   0   0  
1            Marquette  6796117.0  0   0   0   1   0  
2    Boston University        NaN  0   0   0   0   1  
3        Georgia State  1148640.0  0   0   0   0   1  
4                  NaN  5000000.0  0   1   0   0   0  
..                 ...        ... ..  ..  ..  ..  ..  
452           Kentucky  2239800.0  0   1   0   0   0  
453             Butler  2433333.0  0   0   1   0   0  
454                NaN   900000.0  0   0   1   0   0  
455                NaN  2900000.0  1   0   0   0   0  
456             Kansas   947276.0  1   0   0   0   0  

[457 rows x 14 columns]

In [17]:
merged=merged.drop(['Position'],axis=1)
merged

Name            Team  Number  Age  Height  Weight  \
0    Avery Bradley  Boston Celtics       0   25  06-Feb     180   
1      Jae Crowder  Boston Celtics      99   25  06-Jun     235   
2     John Holland  Boston Celtics      30   27  06-May     205   
3      R.J. Hunter  Boston Celtics      28   22  06-May     185   
4    Jonas Jerebko  Boston Celtics       8   29  06-Oct     231   
..             ...             ...     ...  ...     ...     ...   
452     Trey Lyles       Utah Jazz      41   20  06-Oct     234   
453   Shelvin Mack       Utah Jazz       8   26  06-Mar     203   
454      Raul Neto       Utah Jazz      25   24  06-Jan     179   
455   Tibor Pleiss       Utah Jazz      21   26  07-Mar     256   
456    Jeff Withey       Utah Jazz      24   26     7-0     231   

               College     Salary  C  PF  PG  SF  SG  
0                Texas  7730337.0  0   0   1   0   0  
1            Marquette  6796117.0  0   0   0   1   0  
2    Boston University        NaN  0   0   0   0   1  
3        Georgia State  1148640.0  0   0   0   0   1  
4                  NaN  5000000.0  0   1   0   0   0  
..                 ...        ... ..  ..  ..  ..  ..  
452           Kentucky  2239800.0  0   1   0   0   0  
453             Butler  2433333.0  0   0   1   0   0  
454                NaN   900000.0  0   0   1   0   0  
455                NaN  2900000.0  1   0   0   0   0  
456             Kansas   947276.0  1   0   0   0   0  

[457 rows x 13 columns]

In [19]:
merged=merged.drop(['PF'],axis=1)
merged

Name            Team  Number  Age  Height  Weight  \
0    Avery Bradley  Boston Celtics       0   25  06-Feb     180   
1      Jae Crowder  Boston Celtics      99   25  06-Jun     235   
2     John Holland  Boston Celtics      30   27  06-May     205   
3      R.J. Hunter  Boston Celtics      28   22  06-May     185   
4    Jonas Jerebko  Boston Celtics       8   29  06-Oct     231   
..             ...             ...     ...  ...     ...     ...   
452     Trey Lyles       Utah Jazz      41   20  06-Oct     234   
453   Shelvin Mack       Utah Jazz       8   26  06-Mar     203   
454      Raul Neto       Utah Jazz      25   24  06-Jan     179   
455   Tibor Pleiss       Utah Jazz      21   26  07-Mar     256   
456    Jeff Withey       Utah Jazz      24   26     7-0     231   

               College     Salary  C  PG  SF  SG  
0                Texas  7730337.0  0   1   0   0  
1            Marquette  6796117.0  0   0   1   0  
2    Boston University        NaN  0   0   0   1  
3        Georgia State  1148640.0  0   0   0   1  
4                  NaN  5000000.0  0   0   0   0  
..                 ...        ... ..  ..  ..  ..  
452           Kentucky  2239800.0  0   0   0   0  
453             Butler  2433333.0  0   1   0   0  
454                NaN   900000.0  0   1   0   0  
455                NaN  2900000.0  1   0   0   0  
456             Kansas   947276.0  1   0   0   0  

[457 rows x 12 columns]

In [20]:
#encoding with sclearn
from sklearn import preprocessing

In [21]:
#1.Instantiate
enc= preprocessing.OneHotEncoder()

In [33]:
#2.fit
enc.fit(df.Position.values.reshape(-1,1))

OneHotEncoder()

In [ ]:
#reshape

In [23]:
x=np.arange(0,50)

In [24]:
x.ndim

1

In [25]:
x.shape

(50,)

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
x=x.reshape(-1,1)

In [28]:
x.ndim

2

In [29]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

In [34]:
x1=x.reshape(1,-1)
x1.shape


(1, 50)

In [35]:
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [36]:
df.Position.values

array(['PG', 'SF', 'SG', 'SG', 'PF', 'PF', 'PF', 'C', 'PG', 'PG', 'C',
       'PG', 'SG', 'SG', 'C', 'SG', 'SG', 'SG', 'SG', 'PG', 'SG', 'SG',
       'PG', 'C', 'PF', 'PF', 'PF', 'C', 'PG', 'PF', 'SG', 'PF', 'SF',
       'SF', 'PG', 'SF', 'SG', 'PG', 'C', 'PF', 'PF', 'C', 'SF', 'SG',
       'PF', 'SG', 'PF', 'PG', 'SF', 'C', 'SF', 'PF', 'PF', 'PG', 'PG',
       'PF', 'C', 'PG', 'SG', 'SG', 'PF', 'C', 'SF', 'SF', 'SG', 'PF',
       'PG', 'PG', 'C', 'PF', 'SG', 'SF', 'PF', 'PF', 'C', 'PG', 'SG',
       'SF', 'C', 'SG', 'PG', 'C', 'PF', 'SF', 'PG', 'SF', 'SF', 'SF',
       'C', 'SG', 'PF', 'C', 'PF', 'SG', 'SF', 'SF', 'PF', 'SF', 'C',
       'PF', 'PG', 'SF', 'PG', 'SG', 'PG', 'SG', 'PF', 'C', 'SF', 'SF',
       'PG', 'C', 'PG', 'PF', 'PF', 'PF', 'PG', 'C', 'SG', 'SF', 'SF',
       'PG', 'SG', 'SF', 'C', 'SG', 'SG', 'PG', 'C', 'PF', 'PG', 'PG',
       'PF', 'SF', 'SF', 'C', 'SF', 'SG', 'SG', 'SF', 'SF', 'C', 'PG',
       'C', 'SG', 'PF', 'SF', 'C', 'SG', 'PF', 'PG', 'PF', 'PG', 'SG',
    

In [38]:
#3.Transform
onehotlabels = pd.DataFrame(enc.transform(df.Position.values.reshape(-1,1)).toarray())
onehotlabels.head(2)

0    1    2    3    4
0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0

In [41]:
merge_df=(df.join(onehotlabels))
merge_df

Name            Team  Number Position  Age  Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25  06-Feb     180   
1      Jae Crowder  Boston Celtics      99       SF   25  06-Jun     235   
2     John Holland  Boston Celtics      30       SG   27  06-May     205   
3      R.J. Hunter  Boston Celtics      28       SG   22  06-May     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29  06-Oct     231   
..             ...             ...     ...      ...  ...     ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20  06-Oct     234   
453   Shelvin Mack       Utah Jazz       8       PG   26  06-Mar     203   
454      Raul Neto       Utah Jazz      25       PG   24  06-Jan     179   
455   Tibor Pleiss       Utah Jazz      21        C   26  07-Mar     256   
456    Jeff Withey       Utah Jazz      24        C   26     7-0     231   

               College     Salary    0    1    2    3    4  
0                Texas  7730337.0  0.0  0.0  1.0  0.0  0.0  
1            Marquette  6796117.0  0.0  0.0  0.0  1.0  0.0  
2    Boston University        NaN  0.0  0.0  0.0  0.0  1.0  
3        Georgia State  1148640.0  0.0  0.0  0.0  0.0  1.0  
4                  NaN  5000000.0  0.0  1.0  0.0  0.0  0.0  
..                 ...        ...  ...  ...  ...  ...  ...  
452           Kentucky  2239800.0  0.0  1.0  0.0  0.0  0.0  
453             Butler  2433333.0  0.0  0.0  1.0  0.0  0.0  
454                NaN   900000.0  0.0  0.0  1.0  0.0  0.0  
455                NaN  2900000.0  1.0  0.0  0.0  0.0  0.0  
456             Kansas   947276.0  1.0  0.0  0.0  0.0  0.0  

[457 rows x 14 columns]

In [48]:
from sklearn.preprocessing import LabelEncoder
#instantiate Label Encoder
le=LabelEncoder()
#encode single column status
df.Team= le.fit_transform(df.Team)


In [49]:
df.head(20)

Name  Team  Number Position  Age  Height  Weight  \
0             Avery Bradley     1       0       PG   25  06-Feb     180   
1               Jae Crowder     1      99       SF   25  06-Jun     235   
2              John Holland     1      30       SG   27  06-May     205   
3               R.J. Hunter     1      28       SG   22  06-May     185   
4             Jonas Jerebko     1       8       PF   29  06-Oct     231   
5              Amir Johnson     1      90       PF   29  06-Sep     240   
6             Jordan Mickey     1      55       PF   21  06-Aug     235   
7              Kelly Olynyk     1      41        C   25     7-0     238   
8              Terry Rozier     1      12       PG   22  06-Feb     190   
9              Marcus Smart     1      36       PG   22  06-Apr     220   
10          Jared Sullinger     1       7        C   24  06-Sep     260   
11            Isaiah Thomas     1       4       PG   27  05-Sep     185   
12              Evan Turner     1      11       SG   27  06-Jul     220   
13              James Young     1      13       SG   20  06-Jun     215   
14             Tyler Zeller     1      44        C   26     7-0     253   
15         Bojan Bogdanovic     2      44       SG   27  06-Aug     216   
16             Markel Brown     2      22       SG   24  06-Mar     190   
17          Wayne Ellington     2      21       SG   28  06-Apr     200   
18  Rondae Hollis-Jefferson     2      24       SG   21  06-Jul     220   
19             Jarrett Jack     2       2       PG   32  06-Mar     200   

              College      Salary  
0               Texas   7730337.0  
1           Marquette   6796117.0  
2   Boston University         NaN  
3       Georgia State   1148640.0  
4                 NaN   5000000.0  
5                 NaN  12000000.0  
6                 LSU   1170960.0  
7             Gonzaga   2165160.0  
8          Louisville   1824360.0  
9      Oklahoma State   3431040.0  
10         Ohio State   2569260.0  
11         Washington   6912869.0  
12         Ohio State   3425510.0  
13           Kentucky   1749840.0  
14     North Carolina   2616975.0  
15                NaN   3425510.0  
16     Oklahoma State    845059.0  
17     North Carolina   1500000.0  
18            Arizona   1335480.0  
19       Georgia Tech   6300000.0