In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Salary_Data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
x=df['YearsExperience']
y=df['Salary']

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
object = StandardScaler()

x = object.fit_transform(x.values.reshape(-1,1))

In [8]:
x

array([[-1.51005294],
       [-1.43837321],
       [-1.36669348],
       [-1.18749416],
       [-1.11581443],
       [-0.86493538],
       [-0.82909552],
       [-0.75741579],
       [-0.75741579],
       [-0.57821647],
       [-0.50653674],
       [-0.47069688],
       [-0.47069688],
       [-0.43485702],
       [-0.29149756],
       [-0.1481381 ],
       [-0.07645838],
       [-0.00477865],
       [ 0.21026054],
       [ 0.2461004 ],
       [ 0.53281931],
       [ 0.6403389 ],
       [ 0.92705781],
       [ 1.03457741],
       [ 1.21377673],
       [ 1.32129632],
       [ 1.50049564],
       [ 1.5363355 ],
       [ 1.78721455],
       [ 1.85889428]])

In [14]:
from sklearn.linear_model import LinearRegression


In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.25,random_state=25)

In [16]:
lr = LinearRegression()

In [17]:
lr.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred=lr.predict(X_test)
y_pred

array([ 82908.82590531,  64294.59557196,  41026.80765526,  61502.46102195,
       108038.03685534, 116414.44050535,  63363.88405529,  68948.15315529])

In [19]:
test_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
test_rmse

6134.757428646659

In [20]:
lr.score(X_train,y_train)

0.960352162107771

In [21]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 4)

x_poly_train = poly.fit_transform(X_train)
x_poly_test = poly.fit_transform(X_test)

lr2 = LinearRegression()
lr2.fit(x_poly_train, y_train)

LinearRegression()

In [22]:
print(lr2.coef_)

[    0.         29732.82785825  2985.30924117 -1978.76850127
  -556.55333496]


In [23]:
print(lr2.intercept_)

75261.50276458659


In [24]:
y_pred_poly = lr2.predict(x_poly_test)
y_pred_poly

array([ 82728.03462646,  62106.80271263,  43311.57335678,  59387.90273248,
       111002.21303056, 117711.25235058,  61187.23689796,  66893.11354081])

In [25]:
mean_squared_error(y_test, y_pred_poly)

33416437.7416283

In [26]:
r2_score(y_test, y_pred_poly)

0.9501004766160434